### ISSUE TITLE
Detect Pandas errors

### ISSUE THREAD

**Issue by YZ-eng** [vitsalis/PyCG#3]
**shell:** 
    `pycg --package pandas-1.2.3 $(find pandas-1.2.3 -type f  -name "*.py")`
**Got the following error：**
`Traceback (most recent call last):
  File "/usr/local/bin/pycg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pycg/__main__.py", line 56, in main
    cg.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/pycg.py", line 99, in analyze
    self.class_manager, self.module_manager)
  File "/usr/local/lib/python3.7/site-packages/pycg/pycg.py", line 89, in do_pass
    processor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 202, in visit_Import
    self.analyze_submodule(modname)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 202, in visit_Import
    self.analyze_submodule(modname)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 292, in visit_FunctionDef
    super().visit_FunctionDef(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 70, in visit_FunctionDef
    self.visit(stmt)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 206, in visit_ImportFrom
    self.visit_Import(node, prefix=node.module, level=node.level)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 188, in visit_Import
    self.analyze_submodule(imported_name)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 66, in analyze_submodule
    self.module_manager, modules_analyzed=self.get_modules_analyzed())
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 463, in analyze_submodule
    visitor.analyze()
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 485, in analyze
    self.visit(ast.parse(self.contents, self.filename))
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 111, in visit_Module
    super().visit_Module(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 61, in visit_Module
    self.generic_visit(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 292, in visit_FunctionDef
    super().visit_FunctionDef(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 70, in visit_FunctionDef
    self.visit(stmt)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/preprocessor.py", line 308, in visit_Assign
    self._visit_assign(node.value, node.targets)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 192, in _visit_assign
    do_assign(decoded, target)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 181, in do_assign
    do_assign(decoded[pos], elt)
  File "/usr/local/lib/python3.7/site-packages/pycg/processing/base.py", line 180, in do_assign
    if pos < len(decoded):
TypeError: object of type 'Definition' has no len()`

**Comment by Mryanhehe** [comment]
I meet the same bug, could I ask that have u known how to solve it?

**Comment by vitsalis** [comment]
A fix for that has been pushed on the `develop` branch.
