### ISSUE TITLE
make test occur a error

### ISSUE THREAD

**Issue by PeteLing** [vitsalis/PyCG#45]
I try in Python3.7 and Python3.10, It occurs the same error.
Is  it because the mock version? Can you provide a **requirements.txt**?

```
root@9b6f438e0ef0:~/PyCG# make test
python3 -m unittest discover -s pycg/tests -p "*_test.py"
..............F.............E
======================================================================
ERROR: test_handle_module (scopes_test.ScopeManagerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/PyCG/pycg/tests/scopes_test.py", line 55, in test_handle_module
    items = sm.handle_module("root", "", "")
  File "/root/PyCG/pycg/machinery/scopes.py", line 55, in handle_module
    process(modulename, None, symtable.symtable(contents, filename, compile_type="exec"))
  File "/root/PyCG/pycg/machinery/scopes.py", line 34, in process
    if table.get_name() == 'top' and table.get_lineno() == 0:
AttributeError: 'MockTable' object has no attribute 'get_lineno'

======================================================================
FAIL: test_handle_import (imports_test.ImportsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/PyCG/pycg/tests/imports_test.py", line 182, in test_handle_import
    mock_import.assert_called_once_with(".mod2", package="mod1")
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 958, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 945, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: import_module('.mod2', package='mod1')
Actual: import_module('', package='mod1')

----------------------------------------------------------------------
Ran 29 tests in 0.006s

FAILED (failures=1, errors=1)
make: *** [Makefile:2: test] Error 1
```

**Comment by gdrosos** [comment]
Closing as resolved due to #53 and #55
