### ISSUE TITLE
Not being able to run PyCG from source due to circular import(?)

### ISSUE THREAD

**Issue by thisrabbit** [vitsalis/PyCG#63]
Hi, I would like to run PyCG from the source, however on both windows/ubuntu(wsl) with Python 3.10/3.9, trying `python ./pycg/__main__.py -h` would throw an **ImportError**:

```
/home/*/.virtualenvs/PyCG/bin/python /home/*/PyCG/pycg/__main__.py 
Traceback (most recent call last):
  File "/home/*/PyCG/pycg/__main__.py", line 4, in <module>
    from pycg import formats
  File "/home/*/PyCG/pycg/pycg.py", line 23, in <module>
    from pycg import utils
ImportError: cannot import name 'utils' from partially initialized module 'pycg' (most likely due to a circular import) (/home/*/PyCG/pycg/pycg.py)
```

I am relatively not familiar with this problem and would like to learn how to properly config the project so that it can be successfully launched. Also, if it is possible, it would be more beginner-friendly if we could add a `how to set up/contribute from source` section etc. to README. Sorry for bothering you with this :(

**Comment by gdrosos** [comment]
You can run the project from source code using the argument `-m`, which  runs the PyCG module as a script:

`python -m pycg -h`

**Comment by thisrabbit** [comment]
Thank you, this effectively resolved my issue!
